- hosts: node1
  tasks:
    - file:
        path: /home/ec2-user/.kube
        state: directory
        owner: ec2-user
        group: ec2-user
    - fetch:
        src: /root/.kube/config
        dest: /home/ec2-user/.kube/config
        flat: yes
      become: yes
    - replace:
        path: /home/ec2-user/.kube/config
        regexp: "127.0.0.1"
        replace: "{{ansible_default_ipv4.address}}"
      delegate_to: localhost
